version: '2'
services:
  db:
    image: postgres:9
  web:
    build: .
    links:
      - db
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    volumes_from:
      - gems
  gems:
    image: busybox
    volumes:
      - /ruby_gems