# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ecccb2caf904ed0e13a19dd34bdec9d53ddfaa0a6f3d6a506dd8c81ca1ec003fb4df457cfd41b1a13ba24045b998587fd887c53e39d2f88229a1a620c71ec4

test:
  secret_key_base: 7544d8870b8a666bf85354a68675baaedd62ad080e2fcbeca82bee16eeb7b4718be845e8db1bee0eab4a5281f6d0627a60d473e4032d7658dd5ba9db66a4bf37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
